server:
  port: 8084

spring:
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/music
    username: music
    password: music
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
